spring:
  application:
    name: prices-service
  banner:
    location: price.banner

  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: price
    password: denys

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: WARN
    org.springframework: WARN
