spring:
  application:
    name: price-service
    version: 0.0.1
  banner:
    location: price.banner

  datasource:
    url: jdbc:h2:mem:pricesdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: price
    password: denys

  sql:
    init:
      mode: always
      platform: h2

  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    org.springframework.boot.context.properties: DEBUG

